export type UUID = string;

export interface IPart {
  part_id: string,
  user_id: string,
  status: 'active' | 'inactive',
  company_id: string,
  user_name: string,
  name: string,
  unit_system: string,
  customer_name: string,
  file_type: string,
  file_url: string,
  material_standard: string,
  material_category: string,
  material_grade: string,
  material_shape: string,
  material_cost: number,
  stock_qty_per_lot: number,
  lots_count: number,
  scrap_cost: number,
  gross_weight: number,
  net_weight: number,
  profit: number,
  tolerance_standard: string,
  length: number,
  breadth: number,
  width: number,
  diameter: number,
  outer_diameter: number,
  thickness: number,
  wall_thickness: number,
  web_thickness: number,
  flange_thickness: number,
  side: number,
  flat_to_flat_distance: number,
  leg_1: number,
  leg_2: number,
  flange_width: number,
  web_height: number,
  coil_weight: number,
  created_at: number,
  is_deleted: boolean,
}
